- content/en/docs/Concepts/Custom resource definitions/_index.md
- content/en/docs/Concepts/Custom resource definitions/catalog-source.md
- content/en/docs/Concepts/Custom resource definitions/cluster-service-version.md
- content/en/docs/Concepts/Custom resource definitions/intall-plan.md
- content/en/docs/Concepts/Custom resource definitions/operator-group.md
- content/en/docs/Concepts/Custom resource definitions/subscription.md
- content/en/docs/Concepts/_index.md
- content/en/docs/Concepts/additional-concepts.md
- content/en/docs/Concepts/olm-architecture.md
I have added Concepts section which talks about OLM architecture, and a subsection which has individual pages for OLM core concepts. Could you please review? Thanks!
> Added Concepts section for OLM Documentation

- themes/docsy/assets/scss/_footer.scss
- themes/docsy/layouts/partials/footer.html
Add the netlify badge to footer so that the site can be submitted for the
netlify OpenSource hosting plan.
> fix: add netlify badge to footer

- content/en/_index.html
Various improvements to text on just the landing page: simplify and make the descriptions more clear for new OLM users.
> fix: edit landing page text

- content/en/docs/Tasks/install-operator-with-olm.md
Adding information on:
1. That you need to create an operator group before installation into a namespace
2. that the operator group is tied to the install mode of the operator 
3. Link to the operator group docs for further information
> Explaining the need for operator group during install docs

- content/en/docs/Tasks/packaging-an-operator.md
OLM currently has a documentation gap around which objects are supported in bundles. This PR adds some information on supported objects to the new doc site.
> feat: add section on supported bundle objects

- content/en/docs/Concepts/crds/CatalogSource.md
At quay.io/operatorhubio/catalog:latest there is now an index image maintained by the pipeline reflecting the content of https://github.com/operator-framework/community-operators
> change catalog example to index image

- content/en/docs/_index.md
this is a link fix, I found that the link was pointing to the wrong location, instead of operator-sdk it should be pointing to operator-lifecycle-manager.
> fix link from pointing to sdk docs and instead point to olm docs

- assets/scss/_docs.scss
When hovering over a link icon, the whitespace next to it would be underlined, which looked weird.
> remove errant underline from header links

- assets/scss/_docs.scss
- content/en/docs/Concepts/olm-architecture/dependency-resolution.md
- content/en/docs/Reference/_index.md
- layouts/shortcodes/mermaid.html
- themes/docsy/layouts/partials/head.html
For now, I've added support for a mermaid shortcode. It would be nicer to pre-render them, and use a markdown code fence to indicate mermaid content (which would match hackmd), but this will get us running for now.
> Add docs for dependency resolution

- content/en/docs/Concepts/olm-architecture/dependency-resolution.md
the previous doc indicated that there was a "minimization" step which
preferred solutions that had fewer operators. this is not the case
(it was, briefly, during development of the new resolver), and the
guidance is updated to reflect that.
> Correct dependency docs

- content/en/docs/Concepts/crds/subscription.md
Hi, thank you for providing such the great product 👍 
When I added a subscription resource to my cluster, I got the following error:
```
error: error validating "...": error validating data: ValidationError(Subscription.spec): unknown field "approval" in com.coreos.operators.v1alpha1.Subscription.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
Seeing [the CRD definition](https://github.com/operator-framework/operator-lifecycle-manager/blob/7988750a76c02530a72e77fff67705d4b2c0a9c9/manifests/0000_50_olm_00-subscriptions.crd.yaml#L1635-L1638), `spec.installPlanApproval` seems be correct and worked on my cluster.
If this would help this project.
> Replace `spec.approval` field in subscription resource with `spec.installPlanApproval`

- content/en/docs/Tasks/install-operator-with-olm.md
This commit removes the nonexistent `spec.approval` field in an example subscription
with the `spec.installPlanApproval` field.
> Replace nonexistent field in example subscription

- content/en/docs/Tasks/creating-operator-manifests.md
The `Package your operator` doc primarily discusses creating the CSV, as
opposed to packaging the created manifests to create an operator bundle
(which is the next step). This PR renames the doc to include a more
appropriate heading.
It also fixes the link in the doc to the Concepts/dependency-resolution
doc.
> Rename Core task `Package your operator` to `Create operator manifests`

- .github/workflows/lint.yaml
- .travis.yml
Migrate to using Github actions to run the linting check on a per-PR basis.
Remove the .travis configuration file as it's no longer necessary with the introduction of the linting workflow added.
> Migrate to using GitHub actions

- content/en/about/_index.html
- content/en/docs/Tasks/creating-operator-manifests.md
Update the content/* documentation and update any broken links that the
CI linting hack script was exposing:
```bash
docker run --rm -v olm-html:/target mtlynch/htmlproofer /target --empty-alt-ignore --http-status-ignore 429 --allow_hash_href
Running ["ScriptCheck", "ImageCheck", "LinkCheck"] on ["/target"] on *.html... 
Checking 149 external links...
Ran on 43 files!
- /target/about/index.html
*  External link https://sdk.operatorframework.io/docs/installation/install-operator-sdk failed: 404 No error
*  External link https://sdk.operatorframework.io/docs/installation/install-operator-sdk/ failed: 404 No error
*  External link https://sdk.operatorframework.io/docs/installation/install-operator-sdk/#compile-and-install-from-master failed: 404 No error
*  External link …
```
> content: Fix broken links and internal links not resolving

- content/en/docs/contribution-guidelines/upgrade-graphs.md
- themes/docsy/layouts/partials/head.html
The goal of this PR is to document a definition that should be used in the upgrade graphs. 
**Motivation**
Define a standard to communicate with others about the upgrade graphs. We can probably in the future link this new doc/section such as  "to understand the legend in the diagrams in this doc, see the section Standards and definitions in the Upgrade Graphs Diagrams doc". Also, it is helpful for we understand the user's scenarios when they need our help. So, this doc will help then know how thy a use the editor online to describe their scenarios as well.  
See its preview here: https://deploy-preview-97--operator-lifecycle-manager.netlify.app/docs/contribution-guidelines/upgrade-graphs/
> Add diagram doc for upgrade graphs

- content/en/docs/advanced-tasks/operator-scoping-with-operatorgroups.md
This commit fixes an example OperatorGroup in developer documentation
that had an incorrect spec.
> Fix OperatorGroup Documentation Example

- content/en/docs/contribution-guidelines/local-docs.md
- hack/ci/link-check.sh
Update the hack/ci/lint-check.sh script and expose an environment
variable that injects extra container run options. This is particularly
useful in the case you want to run this as a privileged container, or
you want to disable any selinux permissions.
Update the README and give a brief description of what the linting
script is trying to accomplish and add a note about disabling selinux
permissions if you're getting permission denied errors when attempting
to mount the volume when building the site.
> README,hack: Update the linting script and add instructions for running locally

- content/en/docs/contribution-guidelines/local-docs.md
- hack/ci/link-check.sh
hack/ci: Support overriding the default container engine (docker) with podman
using the `$CONTAINER_ENGINE` environment variable.
content: Update the `local-docs.md` documentation and document how you may
override the default container engine (docker) to using podman.
> hack,content: Support overriding container engine in linting script

- .github/workflows/lint.yaml
Rename top-level workflow from `lint` to `test`.
Rename the `unit` to `lint`.
Split up the submodule initialization and running the linting script.
> .github: Update the linting workflow check

- content/en/docs/best-practices/common.md
Add info over the --optinal-values=k8s=1.22 usage. 
More info:
- https://github.com/operator-framework/operator-sdk/pull/4693
- https://github.com/operator-framework/enhancements/blob/master/enhancements/operator-hub-check.md
> doc: add option to check the bundle against k8s version

- content/en/docs/Tasks/install-operator-with-olm.md
- The `[Once you have a catalog of operators loaded onto the cluster via a `CatalogSource`] [create-catsrc-doc]` had a space in between, which resulted in the link not rendering correctly.
- A recent PR updated the location of the channel-def reference to a link that doesn't exist. That was surfacing in the lint job in the following output:
```
c02a5f3da18c: Pull complete
Digest: sha256:505df5f98139b81fd3563b385134c5a784b58bfc8d5a4ece57fa2cbe58b3144f
Status: Downloaded newer image for mtlynch/htmlproofer:latest
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["/target"] on *.html...
Checking 141 external links...
- /target/docs/tasks/install-operator-with-olm/index.html
*  internally linking to channel-def, which does not exist (line 678)
<a href="channel-def">channel</a>
Ran on 44 …
```
> content: Fix unrendered/broken links

- content/en/docs/Tasks/install-operator-with-olm.md
Heyo OLM folks :wave: :smiley: 
According to https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.18.1/crds.yaml the field is named `installPlanApproval`.
> rename subscription.spec.approval to .installPlanApproval

- content/en/docs/Tasks/creating-operator-bundle.md
Add info about new validator to check the bundles against the required criteria to dealing with deprecated APIs for CRDs and the bundles which will be published on the community-operators (https://github.com/operator-framework/community-operators/tree/master/community-operators).
> add info about the community operator validator

- content/en/docs/contribution-guidelines/_index.md
Update the contribution guidelines and add a link to the Docsy
documentation instead of the broken `[Docsy user guide](wherever it goes)`
reference that's currently being deployed.
> content: Add link to the Docsy docs in the contribution guidelines

- content/en/docs/best-practices/channel-naming.md
- Replace `preview` with `candidate` for channel naming check. 
- Improve channels names statements and descriptions 
- Add a note to clarifies the convention motivation
**Motivation**
That was checked that the most appropriated convention name would be candidate instead of preview.
> feat: update the channel naming conv

- content/en/docs/Concepts/operators-on-cluster.md
- content/en/docs/Tasks/install-operator-with-olm.md
- content/en/docs/Tasks/uninstall-operator.md
Signed-off-by: Josh Gwosdz <jgwosdz@redhat.com>
> cleanup: rename `subscription.spec.approval` to `subscription.spec.installPlanApproval`

- content/en/docs/Concepts/crds/clusterserviceversion.md
- content/en/docs/Tasks/creating-operator-manifests.md
- example name was misleading  (should be `<plural>.<group>`)
- added clarification for where the values for each field should come from
> clarify the customresourcedefinitions example

- content/en/docs/best-practices/channel-naming.md
Version numbers, on their own, are ambiguous and could be referring to either product or operator version itself.
If I am creating a Subscription to channel `1.x` of `3scale-operator` (note: /not/ of `3scale` - the product), is it really clear that this version is referring to the version of `3scale` (the product) and not to the version of `3scale-operator` (the component)?
As far as I understand when reading these Naming conventions, the intent is for the former (i.e. that the version refers to the product), but does it hurt us to be explicit - by including the product name - and avoid any confusion at all around this?
The problem is that:
a. "3scale operator" is a component that has different versioning than "3scale" (the product). For 3scale 2.10, 3scale operator has version 1.13.0
b. …
> Clarify use of version numbers in channel names

- content/en/about/_index.html
Update the operator capabilities link in the _index.html. This path to
this link was changed in
https://github.com/operator-framework/operator-sdk/commit/60bfe2eb0aedd1ce9b55bb6ddbaebba7d972b4ef#diff-b49ecbfece1c78775e4b1bf5db7420ea14dd59d9baf81ef3903e1a8bd227ebec.
> content: Fix broken link to the operator capabilities SDK documentation

- content/en/docs/Concepts/olm-architecture/operator-catalog/creating-an-update-graph.md
- content/en/docs/Reference/declarative-config.md
- content/en/docs/Reference/file-based-catalogs.md
- content/en/docs/Tasks/creating-an-index.md
- content/en/docs/advanced-tasks/communicating-operator-conditions-to-olm.md
- content/en/docs/contribution-guidelines/upgrade-graphs.md
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
> Initial docs for file-based catalogs

- content/en/docs/Tasks/Troubleshooting/subscription.md
Follow-up to #173 
- Update `offical` -> `official`.
- Update tense.
- Fix various markdown violations (file contains newline, newline
between header and content).
> content/en: Minor updates to the deprecated API troubleshooting documentation

- .github/workflows/lint.yaml
The actions/checkout@v2 has an option to recursively checking out
submodules, so the manual step of checking out the submodules after
checking out the repository is not needed.
> .github/workflow: Remove unneeded submodule checkout step

- content/en/docs/Concepts/olm-architecture/operator-catalog/creating-an-update-graph.md
- content/en/docs/Tasks/creating-a-catalog.md
- content/en/docs/Tasks/make-catalog-available-on-cluster.md
This PR redirects current users of sqllite backed catalogs to the v0.18.z
version of the docs that have behaviour changes from sqllite backed catalogs
to plaintext file backed catalogs.
A follow up PR will discuss the steps for migrating existing sqllite backed
catalogs to plaintext file backed catalogs in a new doc.
> Add redirection from latest to v0.18.z

- content/en/docs/Concepts/olm-architecture/operator-catalog/creating-an-update-graph.md
Update the creating-an-update-graph.md documentation and fix the link
syntax when referencing file-based catalogs.
Signed-off-by: timflannagan <timflannagan@gmail.com>
> content: Fix invalid link syntax in creating-an-upgrade-graph.md

- content/en/docs/Tasks/creating-a-catalog.md
> Fix typo in docs for creating a catalog

- content/en/docs/advanced-tasks/overriding-catalog-source-pod-scheduling-configuration.md
- content/en/docs/best-practices/channel-naming.md
Signed-off-by: Per G. da Silva <perdasilva@redhat.com>
This PR adds the end-user documentation for how to use the new `grpcPodConfig` attribute to configure CatalogSource pod scheduling. This PR also updates a ded lnik.
> Add catalog pod scheduling config documentation

- content/en/docs/advanced-tasks/configuring-olm.md
This commit introduces a document that outline  how to configure
OLM's through the OLMConfig CRD.
> Introduce OLM Configuration Document

- content/en/docs/Tasks/creating-operator-manifests.md
See https://github.com/operator-framework/operator-registry/blob/master/pkg/lib/bundle/supported_resources.go
1. Reordered list to match order of list in operator registry source code (this will make it easier to compare/maintain)
2. Added `ConsoleQuickStart`, `ConsoleCLIDownload`, and `ConsoleLink` to the list of supported kinds.
3. Fixed case for `ConsoleYAMLSample`
> Update list of supported bundle manifests

- content/en/docs/Reference/file-based-catalogs.md
Fixes general formatting and grammar within the FBC document.
The None compound constraint was recently deprecated in favor
of using the Not compound constraint. Any references to the
None compound constraint in this document have been changed
to Not to adhere to the new guidelines.
> Update FBC Document

- content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
Fixes: https://github.com/operator-framework/operator-registry/issues/912
I also fixed the comments about the version of **OPM** and **OLM** that is required for dependencies.yaml and properties.yaml.  This is based off of looking the commits for these PRs.
> Add properties.yaml to dependencies

- themes/docsy/layouts/partials/footer.html
- themes/docsy/layouts/partials/head.html
This PR removes a RedHat specific script and the RedHat Privacy
statement link from the website.
> (chore) Remove RedHat links

- content/en/docs/best-practices/channel-naming.md
We are proposing some additionals on its [documentation](https://github.com/operator-framework/olm-docs/pull/232/files). **What is the delta?**
- Clarifies why the terminologies tech-preview or preview is not in the convention
- We added as the prefix of the operator visions the `v` (i.e. stable-v2, stable-v2.3 ) to better clarifies it because of the scenario where the channel name has ONLY the Operato major version.
- Also, we added a new section `Recommended upgrade path` to clarifies and exemplifies :
> Within a channel each patch release should be directly upgradable to the HEAD of channel. Use skips or skipRange to provide this behaviour. (i.e. skipRange to publish a patch for `3.6.z`under the`stable-v3.6` would mean setting the skipRange to be `>= 3.5.z. < 3.6.z`, …
> [channel-namming] - supplement recommendations

- content/en/docs/Reference/file-based-catalogs.md
- content/en/docs/Tasks/creating-a-catalog.md
The subcommand for "opm alpha generate" has graduated out of alpha. As a
result references to 'opm alpha generate" should instead reference "opm generate".
Signed-off-by: Tyler Slaton <tyslaton@redhat.com>
> docs: opm alpha generate => opm generate

- content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
The `None` constraint was recently deprecated in favor of `Not`, this
commit replaces all mentions of the `None` constraint with those of
`Not`.
> Replace None constraint mentions with not

- content/en/docs/Reference/veneers.md
Add a section to the veneer document showing the commands required to convert from a File-Based Catalog (FBC) to a basic veneer using `jq` and `yq`. 
Signed-off-by: Rashmi Gottipati <chowdary.grashmi@gmail.com>
> Update doc on how to convert from FBC to a basic veneer

- content/en/docs/Reference/file-based-catalogs.md
Update doc about exclusion of deprecated bundles from File-Based Catalogs based on the `olm.deprecated` property being present on the `olm.bundle` object.
> OPECO-2646: exclude bundles with `olm.deprecated` property when rendering

- content/en/docs/Reference/catalog-templates.md
- content/en/docs/Tasks/creating-a-catalog.md
Upstream docs update to rename veneers to catalog templates.
> OPECO-2664: renaming `veneer` to `catalog template` (or `template` for short)

- content/en/docs/advanced-tasks/unsafe-fail-forward-upgrades.md
Correcting `OperatorGroup.UpgradeStrategy` example to match API definition https://github.com/operator-framework/api/blob/master/pkg/operators/v1/operatorgroup_types.go#L91
> fix: correct OperatorGroup.UpgradeStrategy example

- content/en/docs/getting-started/_index.md
etcd operator no longer works with K8s v1.22+ due to a dependency on a removed API.
Related issues:
* https://github.com/operator-framework/olm-docs/issues/241
* https://github.com/operator-framework/olm-docs/issues/268
* https://github.com/operator-framework/operator-lifecycle-manager/issues/2931
Closes #241
> Updates quick start guide

- content/en/docs/Concepts/olm-architecture/_index.md
Use correct column headings of the OLM - & Catalog Operator resource table.
> Use correct table heading for resource owner

- layouts/partials/navbar.html
`.URL` was depricated and removed in Hugo 0.93.
This is a prep to Hugo upgrade.
> Switches to `.RelPermalink` from `.URL`

- config.toml
- content/en/docs/Reference/catalog-templates.md
- layouts/shortcodes/code_callout.html
- Adds documentation on the composite template introduced to opm via the `opm alpha render-template composite` subcommand
> Add composite template docs

- content/en/docs/Reference/catalog-templates.md
Introducing a new semver template attribute which provides authors the capability to deterministically select generated major or minor channels as default when they are for all other measures "equally stable". 
This attribute is defaulted to minor-version channels if omitted. 
Changes visible in the [Catalog Templates](https://deploy-preview-296--operator-lifecycle-manager.netlify.app/docs/reference/catalog-templates/) page.
> channeltypepreference attribute for semver template; providing hyperlinks to example sections

- config.toml
- netlify.toml
- themes/docsy/layouts/partials/page-meta-lastmod.html
Default value is false. This effectively disables "Last modified" at the end of the page in docs.
As per discussion [here](https://github.com/operator-framework/olm-docs/pull/284#issuecomment-1503440816).
> Removes enableGitInfo config param

- content/en/docs/advanced-tasks/configuring-olm.md
Depends on https://github.com/operator-framework/operator-lifecycle-manager/pull/3046
> Add documentation for packageServerSyncInterval

- content/en/docs/Concepts/crds/clusterserviceversion.md
- content/en/docs/Reference/catalog-templates.md
This addresses the note from #311 informing users that the version spec is necessary for semver templates. 
Solves #311
> OPECO-3073: Add Note for CRD Version Spec

- content/en/docs/Tasks/make-catalog-available-on-cluster.md
* add instructions for image pull from private registry within bundle
* relates to https://github.com/operator-framework/operator-sdk/issues/6622
> Add instructions to reference pull secret from bundle

- content/en/docs/Reference/catalog-templates.md
With merge of https://github.com/operator-framework/operator-registry/pull/1335 there is an explicit schema defining all catalog templates, so this includes updates to document format and processing changes. 
(NB: the examples are sorted for human eyeballs, since go will generally sort all map keys in alpha order which can be a little tougher to read)
> update for `opm alpha convert-template basic`

- content/en/docs/Concepts/crds/operatorgroup.md
Correct typos in the RBAC sections of "provided API resource from a CRD" and "provided API resource from an APIService" after cross-checking with a live cluster and upstream OLM doc in OKD project: https://docs.okd.io/latest/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-rbac_olm-understanding-operatorgroups
> Update operatorgroup.md to fix typos in the doc

- content/en/docs/advanced-tasks/catalog-update-formulary.md
- content/en/docs/advanced-tasks/ship-operator-supporting-multiarch.md
basic catalog template now has its own schema instead of being just a specifically abbreviated general FBC, so the existing formulary is insufficient to treat with it. 
solves #334 
this PR also changes the page formatting to more consistently flow examples as FBC...basic...semver...
Also dealing with a dead GOOS/GOARCH doc link in unrelated pages. 
... and the usual flakiness when we attempt to lint a bunch of links at the same time.
> update the formulary to reflect the new schema for basic catalog templates

- content/en/docs/Tasks/creating-operator-bundle.md
- content/en/docs/Tasks/creating-operator-manifests.md
- content/en/docs/Tasks/install-operator-with-olm.md
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
Fixed some underlying typos in the `content/en/docs/Tasks` directory.
> Added some more nit fixes to the documentation.

- content/en/docs/Tasks/uninstall-operator.md
This commit introduces documentation detailing how to delete an operator
CR.
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
> Add notes on deleting an operator CR

- content/en/docs/Troubleshooting/subscription.md
Update the subscription.md document to explain why a Subscription cannot adopt existing ClusterServiceVersions that are not associated with it.
Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
> Explain why subscriptions do not adopt CSVs

- content/en/docs/Tasks/creating-operator-bundle.md
With original command, will hit error:
```
The directory /root/operator-sdk-samples/go/memcached-operator/deploy/olm-catalog/memcached-operator contains no yaml files
```
The opm version is `v1.21.0`
> Correct opm usage when generate annotations.yaml and Dockerfile

- content/en/docs/Reference/catalog-templates.md
The kube-rbac-proxy from upstream is deprecated. Therefore, it's better not to include it in the examples since we do not promote its usage. PS. it does not seems to bring any value
> Update catalog-templates.md - Remove deprecated image from examples
