operator-framework/olm-docs

- content/en/docs/Advanced tasks/_index.md
- content/en/docs/Advanced tasks/ship-operator-supporting-multiarch.md
- content/en/docs/Advanced tasks/updating-an-operator.md
@anik120, could you please review? thanks!
> Added Advanced Tasks to OLM documentation

- content/en/docs/Tasks/Troubleshooting/clusterserviceversion.md
- content/en/docs/Tasks/install-operator-with-olm.md
- content/en/docs/advanced-tasks/updating-an-operator.md
- content/en/docs/contribution-guidelines/_index.md
- content/en/docs/contribution-guidelines/local-docs.md
This PR addresses review comments from #8
> Address review comments from PR #8

- themes/docsy/layouts/partials/footer.html
adjusts link in footer to go to OF instead of OLM
> fixed link

- assets/scss/_docs.scss
adjusting the style overrides for the docs to align with what is in the SDK site.
> doc-styles

- content/en/docs/Tasks/install-operator-with-olm.md
People like to know how they can keep an Operator at a particular version.
> install a particular operator version

- config.toml
- layouts/partials/hooks/body-end.html
- layouts/partials/hooks/head-end.html
This PR introduces search powered by [algolia](https://algolia.com)
> Implement Algolia search

- assets/scss/_breadcrumb.scss
- assets/scss/_global.scss
- assets/scss/_styles_project.scss
- assets/scss/_variables.scss
1. Removed background bar
2. Corrected padding before breadcrumb text
> Styling for Breadcrumb Navigation

- content/en/docs/Tasks/validate-package.md
Adds description of `api` validation
> add api validation and optional validation

- content/en/docs/getting-started/_index.md
This commit aims to fix a typo on getting started section
> Fix a minor typo on getting started section

- content/en/docs/Concepts/crds/CatalogSource.md
- content/en/docs/getting-started/_index.md
Just fixing a few typos I came across while going through the docs.
> Some typo fixes

- assets/scss/_docs.scss
- layouts/partials/sidebar-tree.html
- themes/docsy/layouts/partials/sidebar-tree.html
just some minor tweaks to fix the sidebar. There is some odd scrolling happening still b/c we have long strings without breaks.
> fixes #1919

- content/en/docs/Tasks/creating-an-update-graph.md
Update the "Creating an udpate graph with OLM" section and replace any
misspelled "update" instances.
> content: Fix misspelling of 'update'

- content/en/docs/contribution-guidelines/upgrade-graphs.md
Improve/fix the label index image legend to clarify that it can be any label and conditional which should be important/relevant to represent in the graph.
> fix label index image description

- content/en/docs/_index.md
Document an introduction to using OLM concentrating on the following core:
1. Brief high level core benefit that describes how using OLM solves cluster admins and developers needs
2. Introduce the building blocks needed to get started as quickly as possible with OLM
3. Link to Getting Started and Advanced doc links
> modified the Introduction and added few more points -- OLM

- OWNERS
- content/en/docs/Concepts/crds/installplan.md
This adds the install plan details along with certain examples of how the operator groups have to be defined for each install plan
> added installplan -- OLM

- content/en/docs/Tasks/test-package-before-shipping.md
Signed-off-by: Venkatramanan Srinivasan <vsriniva@redhat.com>
> OSDK 1641 -- test package before shipping

- content/en/docs/_index.md
Reverts operator-framework/olm-docs#113
@sujil02 @marc-obrien @theishshah this document has to be approved by @dmesser please do not merge this before we've had a chance to review these PRs.
> Revert "Updating Docs to add details on OLM use case"

- content/en/docs/_index.md
Reverts operator-framework/olm-docs#111
@laxmikantbpandhare @theishshah @marc-obrien please reopen this PR so that @dmesser and the olm-dev team can review it and approve it. There were a lot of valuable questions asked in #111 by @jmrodri that were not answered, and are crucial to know the answers to while drafting this document.
Also, I've had to revert a bunch of PRs so far for the same reason, please hold off on powering through these PRs before we've had the chance to address the issues I brought up above.
> Revert "modified the Introduction and added few more points -- OLM"

- content/en/docs/best-practices/common.md
Add doc with common suggestions
**Motivation**
- Share of course this common suggestion, however, also the idea here is to allow us to have the doc for we start to track it.
> doc: add common suggestions

- content/en/docs/_index.md
> modified the Introduction and added few more points -- OLM #111

- content/en/docs/Concepts/operators-on-cluster.md
-Adds documentation about Operators on cluster
Signed-off-by: Sujil02 <sujil.shah@gmail.com>
> Adds documentation about Operators on cluster

- content/en/docs/best-practices/common.md
See : https://github.com/operator-framework/community-operators/pull/3491
> update the best practices link since the content was moved to sdk

- content/en/docs/Tasks/Troubleshooting/subscription.md
Signed-off-by: Daniel Sover <dsover@redhat.com>
> add doc for missing apis error

- content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
> fix typo in dependency resolution docs

- OWNERS
Signed-off-by: perdasilva <perdasilva@redhat.com>
Adds me to the OWNERS file
> Add perdasilva to OWNERS

- content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
- content/en/docs/Reference/file-based-catalogs.md
- content/en/docs/Tasks/creating-operator-manifests.md
A new generic constraint using CEL is introduced in OLM starting 0.20.0.
Signed-off-by: Vu Dinh <vudinh@outlook.com>
> feat(docs): Add generic constraint doc to dependency resolution section

- content/en/docs/advanced-tasks/unsafe-fail-forward-upgrades.md
Note: It would seem that the failing linting action is expected.
> Add Unsafe Fail Forward Upgrades document

- content/en/docs/Concepts/crds/clusterserviceversion.md
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
Added nit fixes to the `ClusterServiceVersion` documentation under `content/en/docs/Concepts/crds/clusterserviceversion.md`.
> Added nit fixes to the documentation

- content/en/docs/advanced-tasks/overriding-operator-pod-affinity-configuration.md
Signed-off-by: perdasilva <perdasilva@redhat.com>
> Add Subscription affinity configuration documentation

- assets/scss/_global.scss
- assets/scss/_homepage.scss
Fixes the following small issues:
1. Primary button hover colour contrast (blue on red background)
2. OLM Features block height adjusted to be in line with other blocks
> Fixes two minor visual issues in the docs site

- content/en/docs/Concepts/olm-architecture/dependency-resolution/_index.md
The package constraint property 'name' is invalid. Update property to match schema, which is 'packageName'.
> Update invalid package constraint property

- content/en/docs/Reference/file-based-catalogs.md
Add docs for olm.deprecation feature #318
> Add deprecation information to docs
